api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "charme-bundle"
type = "function"
uid = "39c9fd5e-a2e9-fc12-a2d8-0a2a117cc74b45a8deb3"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
