/**
 * shopifyCart.js — turn a finished design into Shopify cart line items.
 *
 * Strategy (uses the native Shopify ecosystem, no custom pricing engine):
 *   • The phone-case / tote is a real Shopify product → 1 line item.
 *   • Each charm the brand already sells as a real product/variant → 1 line item
 *     each (quantities merged). Pricing is therefore handled by Shopify natively.
 *   • A shared `_design_token` ties the lines together; the styled-preview proof
 *     image URL + a compact layout JSON ride along as line-item properties so the
 *     maker can reproduce the piece and the customer sees their design in cart.
 *
 * The merchant supplies `variantMap` (charm/product id → Shopify variant id) and,
 * optionally, an `uploadEndpoint` that stores the proof PNG and returns a URL
 * (see app/upload-proof.js). Without an endpoint we still add to cart and pass
 * the layout JSON; the proof can be regenerated by the maker from that JSON.
 */

function token() {
  return 'cd_' + Math.random().toString(36).slice(2, 10) + Date.now().toString(36)
}

async function uploadProof(uploadEndpoint, dataUrl, designToken) {
  if (!uploadEndpoint || !dataUrl) return null
  try {
    const res = await fetch(uploadEndpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ designToken, image: dataUrl }),
    })
    if (!res.ok) throw new Error('upload failed')
    const json = await res.json()
    return json.url || null
  } catch (e) {
    console.warn('[Charmé] proof upload failed, continuing without hosted image', e)
    return null
  }
}

/** Resolve the Shopify variant id for the chosen base product + colour. */
function resolveProductVariant(variantMap, payload) {
  const p = variantMap.products || {}
  // try "<productId>:<colorId>" first, then "<productId>"
  return p[`${payload.product.id}:${payload.product.colorId}`] || p[payload.product.id] || null
}

export function createCartHandler(cfg) {
  const variantMap = cfg.variantMap || { products: {}, charms: {} }
  const routesRoot = (window.Shopify && window.Shopify.routes && window.Shopify.routes.root) || '/'
  const addUrl = `${routesRoot}cart/add.js`.replace('//', '/')

  return async function onPlaceOrder(payload) {
    const baseVariant = resolveProductVariant(variantMap, payload)
    if (!baseVariant) {
      throw new Error(
        `No Shopify variant mapped for "${payload.product.id}". Add it to the block's Variant map.`,
      )
    }

    const designToken = token()
    const proofUrl = await uploadProof(cfg.uploadEndpoint, payload.proofs?.sampleUrl, designToken)

    // merge charms of the same variant into quantities
    const charmCounts = {}
    const unmapped = []
    for (const c of payload.charms) {
      const vid = (variantMap.charms || {})[c.charmId]
      if (!vid) {
        unmapped.push(c.name)
        continue
      }
      charmCounts[vid] = (charmCounts[vid] || 0) + 1
    }
    if (unmapped.length) {
      throw new Error(`These charms aren’t mapped to Shopify variants yet: ${unmapped.join(', ')}`)
    }

    const items = [
      {
        id: Number(baseVariant),
        quantity: 1,
        properties: {
          _design_token: designToken,
          Design: `${payload.charms.length} charms`,
          Finish: payload.product.color,
          ...(proofUrl ? { _proof: proofUrl } : {}),
          _layout: JSON.stringify({
            product: payload.product,
            charms: payload.charms,
            total: payload.total,
          }),
        },
      },
      ...Object.entries(charmCounts).map(([id, quantity]) => ({
        id: Number(id),
        quantity,
        properties: { _design_token: designToken, _role: 'charm' },
      })),
    ]

    const res = await fetch(addUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
      body: JSON.stringify({ items }),
    })
    if (!res.ok) {
      const txt = await res.text().catch(() => '')
      throw new Error(`Shopify cart error: ${res.status} ${txt.slice(0, 120)}`)
    }

    // surface the cart per the merchant's preference
    const mode = cfg.cartRedirect || 'cart'
    if (mode === 'cart') {
      window.location.href = `${routesRoot}cart`.replace('//', '/')
    } else if (mode === 'drawer') {
      document.dispatchEvent(new CustomEvent('charme:added', { detail: { designToken } }))
      // most themes expose a cart drawer; fall back to a refresh of cart sections
      document.dispatchEvent(new CustomEvent('cart:refresh'))
    }
    return { designToken }
  }
}
