/**
 * seed-presets.mjs
 * -------------------------------------------------------------------------
 * Turns reference/presets/layouts.json (built by extract-preset-layouts.mjs)
 * into a D1 seed file that upserts one `presets` row per design, keyed by its
 * Shopify product handle. Design titles come from the DESIGNS list.
 *
 *   node scripts/seed-presets.mjs
 *   wrangler d1 execute charme-catalog --remote --file=reference/presets/seed-presets.sql
 *
 * INSERT ... ON CONFLICT(handle) DO UPDATE keeps re-runs idempotent (and lets a
 * re-extraction overwrite an existing preset) while preserving created_at.
 * -------------------------------------------------------------------------
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DESIGNS } from './fetch-preset-renders.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PRESETS = join(__dirname, '..', 'reference', 'presets')
const TITLES = new Map(DESIGNS)
const q = (s) => `'${String(s).replace(/'/g, "''")}'`

async function main() {
  const layouts = JSON.parse(await readFile(join(PRESETS, 'layouts.json'), 'utf8'))
  const lines = [
    '-- Charmé design presets — generated by scripts/seed-presets.mjs. Do not edit by hand.',
  ]
  let n = 0
  for (const [handle, layout] of Object.entries(layouts)) {
    if (!layout || !(layout.charms || []).length) { console.error(`skip ${handle} (empty)`); continue } // eslint-disable-line
    const title = TITLES.get(handle) || handle
    const productId = layout.productId || 'iphone-16-pro-max'
    const caseColour = layout.caseColourId || 'white'
    const gelColour = layout.gelColourId || 'glitter'
    const json = JSON.stringify(layout)
    lines.push(
      `INSERT INTO presets (handle, title, product_id, case_colour, gel_colour, layout, active, updated_at)\n` +
        `VALUES (${q(handle)}, ${q(title)}, ${q(productId)}, ${q(caseColour)}, ${q(gelColour)}, ${q(json)}, 1, datetime('now'))\n` +
        `ON CONFLICT(handle) DO UPDATE SET title=excluded.title, product_id=excluded.product_id, ` +
        `case_colour=excluded.case_colour, gel_colour=excluded.gel_colour, layout=excluded.layout, ` +
        `active=1, updated_at=datetime('now');`,
    )
    n++
  }
  const out = join(PRESETS, 'seed-presets.sql')
  await writeFile(out, lines.join('\n') + '\n')
  console.log(`wrote ${out} (${n} presets)`) // eslint-disable-line
}

main()
